import Head from 'next/head';
// import Image from 'next/image';
import AudioPlayer from '../components/AudioPlayer/AudioPlayer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Michael Tran&#39;s Music Recommender</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <AudioPlayer />
      </main>
    </div>
  );
}
